name: CI Pipeline

on:
  push:
    branches: [main]

stages:
  - validate
  - test
  - build
  - release
  - deploy

jobs:
  install:
    stage: .pre
    script:
      # define cache dir & use it npm!
      - npm ci --cache .npm --prefer-offline

  lint:
    stage: validate
    script:
      - npm run lint