name: CI Pipeline

on:
  push:
    branches: [main]

stages:
  - validate
  - test
  - build
  - release
  - deploy

jobs:
  install:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout and Set up Node.js
        uses: actions/checkout@v2
      - uses: actions/setup-node@v3
        with:
          node-version: '16'
      - uses: actions/cache@v2
        with:
          path: node_modules
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
      - run: npm ci --cache .npm --prefer-offline

