name: CI Pipeline

on:
  push:
    branches: [main]

stages:
  - validate
  - test
  - build
  - release
  - deploy

jobs:
  install:
    stage: .pre
    script:
      # define cache dir & use it npm!
      - npm ci --cache .npm --prefer-offline

lint:
    if: "!contains(github.event.head_commit.message, 'chore: release') && github.event_name != 'push' || (github.event_name == 'push' && github.ref_type != 'tag')"
    runs-on: ubuntu-latest
    needs: install
    steps:
      
name: Checkout code
      uses: actions/checkout@v3
name: Setup Node.js
    uses: actions/setup-node@v3
    with:
      node-version: 'latest'
name: Install dependencies
  
  run: npm ci --cache .npm --prefer-offline
name: Run lint
run: npm run lint